### ISSUE TITLE
TypeError: Illegal offset type

### ISSUE THREAD

**Issue by wowaTYPO3** [passionweb-manuel-schnabel/ai-seo-helper#13]
TYPO3 12.4.15
ai_seo_helper 0.6.2
PHP 8.2.18
Composer setup.

After installing the extension, I get the following error message in the screenshots when I open the page properties of a standard page.
Sorry, couldn't add a screenshot here as the file would be too big. And copy&paste of the text didn't work either, as the character limit was exceeded.

Screenshots: https://drive.google.com/drive/folders/1bNvshIp6dTaU8ar9OLVGX9_43MkyU6jE?usp=sharing

**Comment by ManuS3009** [comment]
Hey @wowaTYPO3 ,

thanks for the issue.

I think you have installed the AI Suite extension too. This error occured if both of the extensions are installed due to similar timestamps at the registration of the fieldControls in ext_localconf.php and the TCA overrides.

I have just pushed a quickfix which checks if the EXT:ai_suite is loaded and then prevent duplicate registration of the fieldControls.

Can you please checkout the master-Branch and check if everything works?

In the upcoming release I will add the conflict flags to composer.json and ext_emconf.php. Because of the Codesprint I will do this next week at the latest ;-) 

Greetings Manu

**Comment by passionweb-manuel-schnabel** [comment]
Hey @wowaTYPO3 ,

thanks for the issue.

I think you have installed the AI Suite extension too. This error occured if both of the extensions are installed due to similar timestamps at the registration of the fieldControls in ext_localconf.php and the TCA overrides.

I have just pushed a quickfix which checks if the EXT:ai_suite is loaded and then prevent duplicate registration of the fieldControls.

Can you please checkout the master-Branch and check if everything works?

In the upcoming release I will add the conflict flags to composer.json and ext_emconf.php. Because of the Codesprint I will do this next week at the latest ;-)

Greetings Manu

**Comment by wowaTYPO3** [comment]
Thanks for the super quick response. Among other things, I want to show the extension next week in my AI Online Bootcamp, so this works for now. :)
