### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by wowaTYPO3** [passionweb-manuel-schnabel/ai-seo-helper#3]
I just wanted to generate a description with the current version of the extension, and then got this error message in the TYPO3 backend. Probably a problem with openai?
I have tried several times.

{"success":false,"error":"Server error: `POST https:\/\/api.openai.com\/v1\/completions` resulted in a `500 Internal Server Error` response:\n{\n    \"error\": {\n        \"message\": \"Internal server error\",\n        \"type\": \"auth_subrequest_error\",\n        \"param\": n (truncated...)\n"}

**Comment by passionweb-manuel-schnabel** [comment]
Yes, exactly. 

This error message always comes when the API or OpenAI is generally not available (which unfortunately happened from time to time in the last few days).

But I will specifically try to catch this error message and provide better information so that you know that the API is currently unavailable.

**Comment by passionweb-manuel-schnabel** [comment]
I have just released version 0.2.2 and made the mentioned adjustments to the error handling. Now, if the API cannot be reached and if the API key is missing, a more informative notification should appear.

Of course we hope that the accessibility of the API will stabilize in the near future and that we won't see that error message so often anymore ;-)

Thank you for reporting the issue again.
