### ISSUE TITLE
Unerwarteter Fehler [object Object]

### ISSUE THREAD

**Issue by rheinformat** [passionweb-manuel-schnabel/ai-seo-helper#7]
When I hit the "Generate" button, I get the error message "Unerwarteter Fehler [object Object]". I got an Open AI API key. Do I need an OpenAI-Pro account?

**Comment by passionweb-manuel-schnabel** [comment]
Hey Axel,

thank you for your message. 

You do not need a pro account. 

I is possible that the OpenAI API is currently not available (unfortunately it happens from time to time). 

In order to be able to analyze the behavior more precisely, a few more information would be very good (TYPO3 version, extension version, which field). You are also welcome to send me the log entry if you have it to hand. 

Greetings Manu

**Comment by rheinformat** [comment]
Hey Manu,
thanks for your quick response. I'm using TYPO3 Version 11.5.27, AI SEO Helper 0.5.1. PHP Version 7.4.33. I can find the following message in the log:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1436717279: The given status code is not a valid HTTP status code | InvalidArgumentException thrown in file /html/typo3/typo3_src-11.5.27/typo3/sysext/core/Classes/Http/Response.php in line 188. Requested URL: https://relaunch.rheinformat.com/typo3/ajax/generate/page-title?token=--AnonymizedToken--

The error occurs permanently and in every field.

Thanks and greetings
Axel

**Comment by passionweb-manuel-schnabel** [comment]
Thanks for the information. The fact is that in a few error handling constellations, the status code is set to "0", which leads to this InvalidArgument exception. 

Will be fixed asap with new version 0.5.2-

**Comment by nilesh-nitsan** [comment]
Hi, I have faced this issue while generating content - 

![image](https://github.com/passionweb-manuel-schnabel/ai-seo-helper/assets/59409022/fe7e3b2d-a3f5-4dde-b833-8cc977d159c6)

TYPO3 v11.5.27 
Extension v0.5.2 is the latest one. 

Let me know if I missed something. 

Your help is really appreciatable,

Thanks!
