### ISSUE TITLE
500 Error while Generating the AI content

### ISSUE THREAD

**Issue by nilesh-nitsan** [passionweb-manuel-schnabel/ai-seo-helper#8]
Hi, I have faced this issue while generating content - 

![image](https://github.com/passionweb-manuel-schnabel/ai-seo-helper/assets/59409022/fe7e3b2d-a3f5-4dde-b833-8cc977d159c6)

TYPO3 v11.5.27 
Extension v0.5.2 is the latest one. 

Let me know if I missed something. 

Your help is really appreciatable,

Thanks!

_Originally posted by @nilesh-nitsan in https://github.com/passionweb-manuel-schnabel/ai-seo-helper/issues/7#issuecomment-1585481569_

**Comment by passionweb-manuel-schnabel** [comment]
Hey Nilesh, 

thanks for reporting the issue. I will take a closer look at the problem later and give you a response as soon as possible.

Greetins Manu

**Comment by passionweb-manuel-schnabel** [comment]
Hey @nilesh-nitsan,

I have now added an exception that catches the error. Since the Preview Uri is only used in certain cases, this could help you.

It is published on the master branch.

Nonetheless, I'd like to get to the bottom of this in more detail. I looked at the buildUri() function inside the PreviewBuilder (typo3/sysext/backend/Classes/Routing/PreviewUriBuilder.php). Unfortunately only the "UnableToLinkToPageException" is thrown there and no more detailed information is returned. Could you possibly send me the parameters you set/existing there (line 165 to 171)?

![PreviewUriBuilder](https://github.com/passionweb-manuel-schnabel/ai-seo-helper/assets/120183093/b4bdddba-0295-4391-aff6-12d1b3e87710)


 Gladly via [Slack](https://typo3.slack.com/team/U02FG49J4TG) if you don't want to share the parameters publicly.

I would be happy if we could analyze this in more detail because I have not been able to reproduce the error so far.

Greetings Manu

**Comment by passionweb-manuel-schnabel** [comment]
Unfortunately, I couldn't adopt the solution of your pull request 1to1, because I don't have a current ContentObject of the request to create the PreviewUri. Since I call the requests via AJAX and in the backend context, I think it would be too complicated. But I have modified the generation of the PreviewUri based on your help!

But I the current state is a good way to handle this scenario. Thanks for your hint and your suggestions!
